
CREATE TABLESPACE PRODUCTION_MANAGEMENT
    DATAFILE 'D:\课\整理\二工大\Oracle数据库\Experiment\Enterprise\建模\PRODUCTION_MANAGEMENT.DBF'
    SIZE 100M
    AUTOEXTEND ON
    NEXT 10M;

DROP TABLESPACE PRODUCTION_MANAGEMENT;
