

SELECT * FROM ORD;
------------------------------------------------------------------
-- VIEW CUSTOMR_ORDERED_INFO: 用户订单信息(用户查询订单信息)
------------------------------------------------------------------
CREATE OR REPLACE VIEW CUSTOMR_ORDERED_INFO
AS
SELECT 
ORD.ORDID,CUSTOMER.CUSTID,CUSTNAME,CUSTOMER.CUSTADD,
CUSTPHONE,PRODUCT.PRONAME,QTY,ORDDATE,D_DATE
FROM ORD,PRODUCT,CUSTOMER
WHERE ORD.PROID=PRODUCT.PROID AND ORD.CUSTID=CUSTOMER.CUSTID
ORDER BY CUSTNAME;

SELECT * FROM CUSTOMR_ORDERED_INFO;
DROP VIEW CUSTOMR_ORDERED_INFO;

GRANT SELECT ON CUSTOMR_ORDERED_INFO TO ABEL,ALAN,DAN;
------------------------------------------------------------------
-- PROCEDURE SHOW_ORDER_CUSTOMER: 查询订单编号输出客户信息和订单信息
------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SHOW_ORDER_CUSTOMER
(IN_ID IN CUSTOMR_ORDERED_INFO.ORDID%TYPE)
AS 
   OUT_ORD CUSTOMR_ORDERED_INFO%ROWTYPE;
BEGIN
   SELECT * INTO OUT_ORD FROM CUSTOMR_ORDERED_INFO WHERE ORDID=IN_ID;
   DBMS_OUTPUT.PUT_LINE('Customer: '||OUT_ORD.CUSTNAME);
   DBMS_OUTPUT.PUT_LINE('Address: '||OUT_ORD.CUSTADD);
   DBMS_OUTPUT.PUT_LINE('Phone: '||OUT_ORD.CustPhone);
   DBMS_OUTPUT.PUT_LINE('Product_ordered: '||OUT_ORD.PRONAME);
   DBMS_OUTPUT.PUT_LINE('Quantity: '||OUT_ORD.QTY);
   DBMS_OUTPUT.PUT_LINE('Ordered Date: '||OUT_ORD.ORDDATE);
   DBMS_OUTPUT.PUT_LINE('D_Data: '||OUT_ORD.D_DATE);
END;

EXECUTE SHOW_ORDER_CUSTOMER('CR09');
DROP PROCEDURE SHOW_ORDER_CUSTOMER;

SELECT * FROM CUSTOMER;
SELECT * FROM ORD;


SELECT * FROM DEPART;

SELECT 
PRODUCT.PRONAME,QTY,ORDDATE,D_DATE
FROM ORD,PRODUCT
WHERE ORD.PROID=PRODUCT.PROID ;

GRANT EXECUTE ON SHOW_ORDER_CUSTOMER TO ABEL,ALAN,DAN;
------------------------------------------------------------------
-- FUNCTION CUSTOMER_CONTACT: CUSTOMER_CONTACT 查找客户联系方式
------------------------------------------------------------------
CUSTOMR_ORDERED_INFO

CREATE OR REPLACE FUNCTION CUSTOMER_CONTACT
(ID IN CUSTOMR_ORDERED_INFO.CUSTID%TYPE)
RETURN CUSTOMR_ORDERED_INFO.CUSTPHONE%TYPE
AS
   PH CUSTOMR_ORDERED_INFO.CUSTPHONE%TYPE;
BEGIN
   SELECT CUSTPHONE INTO PH FROM CUSTOMR_ORDERED_INFO
      WHERE CUSTID=ID;
   RETURN(PH);
END;

DECLARE 
   PH CUSTOMR_ORDERED_INFO.CUSTPHONE%TYPE;
BEGIN
   DBMS_OUTPUT.PUT_LINE(CUSTOMER_CONTACT('C009'));
END;

GRANT EXECUTE ON CUSTOMER_CONTACT TO ABEL,ALAN,DAN;
